const VERBOSE = true;

const MAX_HARVESTERS_PER_SOURCE = 4;

const USE_PATHFINDER = true;

const DEFAULT_MIN_LIFE_BEFORE_NEEDS_REFILL = 700;

export default {
  VERBOSE,
  MAX_HARVESTERS_PER_SOURCE,
  USE_PATHFINDER,
  DEFAULT_MIN_LIFE_BEFORE_NEEDS_REFILL,
};
